### ISSUE TITLE
MapFragment is not fitting screen completely on large devices

### ISSUE THREAD

**Issue by mohand1993** [Sygic/sygic-maps-kit-android#100] opened 2020-04-29 07:56 UTC
Steps to reproduce:

- Run the sample App on a larger device (e.g . Pixel 4 XL)
- Navigate to any stack that displays the MapFragment (e.g. Browse Map - Default)

![device-2020-04-29-093038](https://user-images.githubusercontent.com/5392493/80572935-6311d400-89ff-11ea-9a2d-1021f6ed2d02.png)
![device-2020-04-29-091917](https://user-images.githubusercontent.com/5392493/80572920-5ee5b680-89ff-11ea-9b4f-6ce81ba0ca2c.png)

**Comment by bio007** [comment] 2020-04-29 09:54
@mohand1993 look at the second image - icons like magnifier are correctly placed. Only map is rendered on the smaller portion of the screen.

That means your proposed fix #101 won't help. I think the problem is in the rendering engine not using all the screen so the devs have to fix that.

I don't think this is a problem in the layout.

**Comment by Darxie** [comment] 2020-04-29 12:20
Hi, 

The issue lays within the app itself, not in the rendering engine. 
Thank you very much @mohand1993 for pointing out the problem and for proposing the fix. 

I have linked the pull request to this issue so it will be closed after merging the PR.

**Comment by bio007** [comment] 2020-04-29 12:47
@Darxie true is it will cause the child layout to use all the space of the parent which is ok.

But I would check with 3D team because this means engine is not detecting the resolution of the device correctly for high density large screens (or actually limiting the resolution). If resolution is detected correctly it should cover all the area by itself.

At the end, I agree, it may actually be a viable fix but it will probably decrease the quality of the rendered image or even can deform it for some screen sizes (but hopefully not).

**Comment by Darxie** [comment] 2020-04-29 15:28
Hi, 

I have merged the pull request for the time being as it seems to have fixed the issue (I have tried it on both FullHD and QHD resolutions). 
However, I will check with our 3D team and post an update if we find any bug. In case we do, we will of course try to fix it as soon as possible in the MapsSDK. 

Thank you for your cooperation :)

**Comment by mohand1993** [comment] 2020-04-30 05:52
Thank you all for your support
When will you publish the new version to maven?

**Comment by Darxie** [comment] 2020-05-03 14:36
Hi @mohand1993, I have merged your "workaroud" only here in the GitHub project. I have created a task on our side and we will have a look into it during the nearest sprint. I therefore have no further information on when a new version with a fix will be published. 
You will surely see it in our changelog when it happens. 
Thank you.

**Comment by Darxie** [comment] 2020-05-21 08:00
Hi all,

We have checked this with the 3D team and have found out that this is a problem in the app itself. 
It can be fixed either in the layout or in code just like you have done in the pull request. 

I will be therefore closing this issue shortly.

**Closed as completed** 2021-02-26 09:10 UTC
